### PR TITLE
fix: RCC: Error in 'QuiteRSS.qrc': Cannot find file 'images/quiterss_debug.ico'

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by Funcy-dcm** [comment]
https://github.com/QuiteRSS/quiterss/blob/master/images/quiterss_debug.ico

**Comment by onlyjob** [comment]
I do not see how this file is useful for GNU/Linux build...

**Comment by Funcy-dcm** [comment]
https://travis-ci.org/QuiteRSS/quiterss

**Comment by Funcy-dcm** [comment]
He is in the source code, and it should have no effect on the assembly.

**Comment by onlyjob** [comment]
I see what you mean: you do not have this build problem.
In Debian build we drop `.ico` files from tarball because they make no sense for non-Windows platforms. I'm not even sure if icon would be rendered properly...

**Pull request closed without merging**
