### PR TITLE
Show notifier with 'Recent News', on tray single click

### PR DESCRIPTION
**Pull request by ShamblerBishop**
- 'Recent News' covers all news received since last minimized to tray
- No config options, this feature is disabled if 'single-click-open tray' config is checked
- Avoids open on double-click, by waiting 400ms; make configurable in future

Relates to issue #810

### CODE REVIEW

**Comment by ShamblerBishop** [comment]
Recommend having this in testing for a good amount of time, before official release.

**Comment by ShamblerBishop** [comment]
I didn't intend to land this second set of changes, within the same pull request - have not used git much before. Let me know if I should untangle this, and resubmit in two separate branches/pull-requests.

**Comment by Funcy-dcm** [comment]
Thanks for the help! In the near future I will try to test.

**Comment by ShamblerBishop** [comment]
About to resubmit these changes - closing this first.

**Pull request closed without merging**
